created hamburger menu + dropdown navbar and linked it
antoniatandler/capstone-project pull request #12
Opened 2023-06-07 10:21 UTC by antoniatandler

2023-06-07 11:10 UTC, doemser requested changes
Hi nice PR!

You have several links and buttons in your app that have no function, please remove them with this PR.

Also, your styling seems to be a bit broken, see screenshot. This should be noticeable in QA, but since you know it now you can fix it before.

![Uploading Screenshot 2023-06-07 at 13.10.39.png…]()

Also, I was able to flag a few more adjustments in the code.

2023-06-07 11:10 UTC, doemser commented on components/Heading.js
> +`;
There is no html element called "text"

2023-06-07 11:10 UTC, doemser commented on pages/index.js
>  `;
Move this StyledComponent to another file, as you are using it in multiple places of your project. Please also make sure to not use divs if there are better suiting html tags

2023-06-07 11:10 UTC, doemser commented on components/Heading.js
> +import { FeatureButton } from "@/pages";
This Button should have its own file as you use it in mutliple places.

2023-06-07 11:10 UTC, doemser commented on components/WelcomeMessage/index.js
> +export const StyledImage = styled(Image)``;
What are you using this for? You do not need a StyledComponent if you do not apply styles

2023-06-07 11:10 UTC, doemser commented on components/Heading.js
>    position: fixed;
use flexbox or grid on the parent to position this element, rather than placing it fixed.

2023-06-07 11:10 UTC, doemser commented on components/Heading.js
> +  position: fixed;
Only position the HeadingContainer fixed, and use flexbox or grid to position the children elements within the HeadingContainer

2023-06-07 11:10 UTC, doemser commented on components/Heading.js
> +            </MenuButton>
anchors are not valid children of buttons, if you want your link to look like a button you actually need an anchor component to look like this

2023-06-07 11:10 UTC, doemser commented on components/Heading.js
> +          </MenuItem>
This link leads to a 404 page. If you merge this PR you will have a non functioning link in your live code, this is why dead links are never allowed

2023-06-08 13:24 UTC, doemser requested changes
Hello again :) 

The initial comment of a pull request serves as a historical record of the original state of the pull request, you should not edit in a way that it only comments on the latest changes committed to this Pull Request, better write a new comment after your latest commits, if you want to reason your decisions.

The dropdown menu is only usable if you are scrolled all to the top of the page. If I am on /poses or /poses/[id] the dropdown menu gets stuck on the top post when scrolling. This needs to be changed.

Also I found a few minor things that need to be changed.

2023-06-08 13:24 UTC, doemser commented on components/Heading.js
> +        </HamburgerModel>
For A11y reasons you should use onClick events only on buttons. Other elements with onclick events may not work properly for users with assistive technologies, like screen readers. Buttons also provide keyboard interactivity by default.

2023-06-08 13:24 UTC, doemser commented on components/Heading.js
> +`;
for once, a div is the most appropriate element here

2023-06-08 13:24 UTC, doemser commented on components/Heading.js
> +        </MenuItem> */}
always remove unused code

2023-06-08 13:24 UTC, doemser commented on pages/index.js
> +        <FeatureButton>Feature 4</FeatureButton> */}
remove unused code

2023-06-09 14:15 UTC, JohannSiemens reviewed
Good job, my feedback is minor, so your PR is approved from my side.

2023-06-09 14:15 UTC, JohannSiemens commented on components/Heading.js
I would put this file into a "Heading"-Folder, to have it as a styled component, like you did with all your other components too.

2023-06-13 07:14 UTC, merged